name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: |
        npm install jest eslint
        npm run --silent ci:lint
        npm run --silent ci:test
